### ISSUE TITLE
Adding question about promises

### ISSUE THREAD

**Issue by omer-demir** [h5bp/Front-end-Developer-Interview-Questions#242] opened 2015-01-29 15:56 UTC
Maybe adding questions about promises and also difference between promise and jquery deffer would be nice. With recent changes promises will play important roles.

**Comment by darcyclarke** [comment] 2015-01-30 10:02
Ideally, I'd like to remove all of the jQuery-specific questions... currently they don't really add any value and any future questions should probably be library agnostic (see #230 for more info).

**Comment by phanan** [comment] 2015-01-31 03:47
+1 for removing jQuery questions. If we have jQuery, why don't we have underscore? If we add underscore, why is lodash missing? The list will go on forever.
This repository shouldn't be catered for any specific libraries or frameworks, however popular they are.

**Comment by appleboy** [comment] 2015-01-31 05:09
+1 for removing jQuery question. The same reason with @phanan

**Comment by omer-demir** [comment] 2015-02-04 10:31
+1 for improvement.

**Comment by phanan** [comment] 2015-02-04 16:24
Shouldn't we close this question now that jQuery has been removed? Calling for @darcyclarke and @appleboy.

**Comment by arthurvr** [comment] 2015-02-04 16:37
No, I don't think so. Promises aren't jQuery specific.

**Comment by phanan** [comment] 2015-02-04 16:43
Right, how about a generic

> What is a `promise` and how does it work?

or

> What JavaScript problems is `promised` targeted to solve?

or, a bit more specific:

> What's the difference between a `promise` and callbacks? Which do you prefer, and why?

(Disclaimer: I'm in no way a JS expert).

**Comment by jvalle** [comment] 2015-02-13 03:18
What about a JSNext series of questions, that could include promises?

**Comment by richgilbank** [comment] 2015-02-13 03:34
I don't think a set of ES* questions is worthwhile just yet, keeping in mind the original objective of this project is job interview questions. I doubt there are many places out there that expect significant ES6 expertise a requirement. That said, Promises as a concept - that is, jQuery's Deferreds, ES6 Promises and polyfills, are worthwhile and usable today. If someone wants to draft up a question along the lines of the following, I'd be happy to look it over:
`What is the extent of your experience with Promises and/or their polyfills?`

**Comment by darcyclarke** [comment] 2015-02-17 23:06
Apologize for the delay, I admit I'm playing a bit of `catch` up on this discussion. I'm happy to see we `all` agreed to `reject` library-specific API implementations. I `promise` we'll be better off in the long run for doing that. I'm also `always` glad to see that we're (as a community) not in a `race` to add more questions just for the sake of it; Vetting ideas/topics first and `then` formulating questions around those is the ideal workflow. 

That said, to `resolve` this `pending` issue I'm in favour of `settling` on @richgilbank's proposal. It `fullfills` the primary criteria of an overarching question on *Promises*. 

If no one else has suggestions or editions to that `then`, Rich, you should make a PR.

**Comment by richgilbank** [comment] 2015-02-17 23:11
@darcyclarke Awful. Just awful. :stuck_out_tongue_closed_eyes: 
PR added.

**Comment by darcyclarke** [comment] 2015-02-17 23:14
:smirk:

**Closed** 2015-02-17 23:20 UTC

**Comment by phanan** [comment] 2015-02-19 03:43
Chit-chat (I know the issue is closed): I was reading @darcyclarke's comment from Gmail and asking myself "What the heck with these monospace stuff?" And then I was like "Whoa... Just... Whoa..."

**Comment by masterE** [comment] 2015-02-19 04:33
How can I stop getting emails from all of u

On February 18, 2015, at 7:44 PM, Phan An <notifications@github.com> wrote:

Chit-chat (I know the issue is closed): I was reading @darcyclarke's comment from Gmail and asking myself "What the heck with these monospace stuff?" And then I was like "Whoa... Just... Whoa..."

**Comment by arthurvr** [comment] 2015-02-19 10:06
@masterE By [unsubscribing](https://help.github.com/articles/unsubscribing-from-conversations/)
